### ISSUE TITLE
Question about ROM loading

### ISSUE THREAD

**Issue by bgourlie** [SourMesen/Visual2C02#1]
Very cool project! One question: What roms are supported for loading? Am I correct to assume it supports NROM only?

**Comment by SourMesen** [comment]
Yes, only NROM files are supported.  Arguably, mappers that only have simple bank switching could also probably be emulated reliably with a bit of extra work - but anything more complex than that would just end up being a mix of "low" and "high" level emulation, which sort of defeats the purpose.

FYI, there are also a number of known issues with this at the moment that I never got around to trying to figure out (mostly because it's outside my expertise).   Some more details/info about the development can be read in this thread: https://forums.nesdev.com/viewtopic.php?f=3&t=15334

**Comment by bgourlie** [comment]
That's what I had assumed, but wanted to double-check. I'm considering porting the (surprisingly simple) emulation core to rust and targeting the browser via WebAssembly, which would give near-native speed while having the accessibility of the browser. I'll make sure to give proper attribution if and when I do!

**Comment by bgourlie** [comment]
Repo for my port here if you're curious: https://github.com/bgourlie/nessim
